FROM golang:1.21.1-alpine3.18 AS builder
LABEL authors="s.andryunin"

WORKDIR /usr/local/go/src/

COPY . /usr/local/go/src/
RUN go clean --modcache && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=readonly \
    -o ./bin/hetzner-dns cmd/service/*.go

FROM scratch
WORKDIR /app
COPY --from=builder /usr/local/go/src/bin/hetzner-dns /app/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY ./ca.crt /etc/ssl/certs/

CMD ["/app/hetzner-dns"]
